import Head from "next/head";
import TopBgCard from "../components/TopBgCard";

export default function Home() {
  const SLIDE_COUNT = 10;
  const slides = Array.from(Array(SLIDE_COUNT).keys());
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <TopBgCard />
      </main>
      {/* <EmblaCarousel slides={slides} /> */}
    </div>
  );
}
